### ISSUE TITLE
Word "C++" will trigger auto complete for "C", how can I type "C++" in the editor?

### ISSUE THREAD

**Issue by AeroXi** [steven-tey/novel#24]

**Comment by Azad-Aihub** [comment]
A roundabout way: Enter a space between the two plus signs and delete them later

**Comment by AeroXi** [comment]
> A roundabout way: Enter a space between the two plus signs and delete them later

Yes it is a good way. Is there any better way to implement this ++ feature?

**Comment by Azad-sl** [comment]
**ui/editor/index.tsx**
You can modify this file, for example to change '++' to '%%'

**Comment by Azad-Aihub** [comment]
> > A roundabout way: Enter a space between the two plus signs and delete them later
> 
> Yes it is a good way. Is there any better way to implement this ++ feature?

**ui/editor/index.tsx**
You can modify this file, for example to change '++' to '%%'

**Comment by steven-tey** [comment]
Yes you can – all you need to do is hit `Esc` when the generation starts and it automatically aborts it and gives you your "++" back!

Here's the code for it: https://github.com/steven-tey/novel/blob/main/ui/editor/index.tsx#L109-L130

I've debated between "++" vs "+++", but settled for ++ since it's lesser keystrokes (at the risk of conflicting with more common words/phrases).

**Comment by GLips** [comment]
Cmd+z should work too, but neither of these solutions work great on mobile.

**Comment by SamikshyaKarki0** [comment]
You can use visual studio code if you would like can't you??

**Comment by vd-07** [comment]
@GLips @steven-tey Can we use something like a timegap between the consecutive ++ keypresses to differentiate whether the intention is ++ or Autocomplete? 

Example: If the time diff between two consecutive ++ is more than 500 ms then treat it as intentional otherwise Autocomplete.
